/* eslint-disable max-len */

export const commentsFromServer = [
  {
    id: 1,
    parentId: null,
    userId: 1,
    text: "What if Plato's cave was just a massive LAN party? Hear me out: imagine all these chained gamers, only seeing the shadows of their avatars on the cave wall, and they think that's reality. But when they finally escape, they realize there's an entire world outside their gaming sessions! Mind-blowing, right?",
    createdAt: '2023-03-22T10:00:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 2,
    parentId: 1,
    userId: 2,
    text: "Haha, that's an interesting take on Plato's allegory! It does make you wonder about the nature of our perception and what we consider reality.",
    createdAt: '2023-03-22T10:10:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 3,
    parentId: 1,
    userId: 3,
    text: "I don't know, man. That's a bit of a stretch. But it's a funny way to think about it, I guess!",
    createdAt: '2023-03-22T10:15:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 4,
    parentId: 3,
    userId: 1,
    text: "Well, it's just a playful reinterpretation of the story. Don't take it too seriously!",
    createdAt: '2023-03-22T10:25:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 5,
    parentId: 1,
    userId: 4,
    text: "Actually, that's a great analogy for how gaming can be an escape from reality, yet it can't replace the richness of the real world.",
    createdAt: '2023-03-22T10:30:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 6,
    parentId: null,
    userId: 2,
    text: "If famous philosophers were superheroes, who would they be? Like, would Nietzsche be Batman because he's all about the will to power and the whole 'God is dead' thing? I'm curious to hear your thoughts!",
    createdAt: '2023-03-22T11:00:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 7,
    parentId: 6,
    userId: 3,
    text: "That's an amusing idea! I think Descartes would be like Dr. Strange, as he questioned reality and was a mathematician too. His famous quote 'Cogito, ergo sum' could be his catchphrase!",
    createdAt: '2023-03-22T11:15:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 8,
    parentId: 6,
    userId: 1,
    text: "Haha, good one! I imagine Socrates would be like Captain America because he's all about ethics and justice. He would never back down from a moral argument!",
    createdAt: '2023-03-22T11:30:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 9,
    parentId: 6,
    userId: 4,
    text: 'Kant would be like Iron Man, considering his focus on logic and duty. Plus, he had a strict daily routine, just like Tony Stark!',
    createdAt: '2023-03-22T11:45:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 10,
    parentId: null,
    userId: 3,
    text: "Imagine if Schrödinger's cat was a video game character that could be both alive and dead at the same time. You'd never know its status until you checked your inventory. What kind of game mechanics could we come up with based on that?",
    createdAt: '2023-03-22T12:00:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 11,
    parentId: 10,
    userId: 1,
    text: "Oh, that's a cool concept! The game could involve different dimensions or timelines where the cat's state would affect the storyline or player's abilities. So many possibilities!",
    createdAt: '2023-03-22T12:15:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 12,
    parentId: 10,
    userId: 2,
    text: "We could also have a mechanic where the cat grants you special powers when it's alive, but when it's dead, you face greater challenges. It would add a layer of unpredictability to the game.",
    createdAt: '2023-03-22T12:30:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 14,
    parentId: null,
    userId: 1,
    text: 'What do you think would happen if a philosopher went back in time and met their younger self? How would their discussions change the course of their own philosophy?',
    createdAt: '2023-03-22T15:00:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 15,
    parentId: 14,
    userId: 2,
    text: 'Interesting thought experiment! I guess it would depend on the philosopher and how open they were to changing their beliefs.',
    createdAt: '2023-03-22T15:15:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 16,
    parentId: 15,
    userId: 3,
    text: "That's true. Some philosophers might be more willing to listen and learn, while others could be quite stubborn.",
    createdAt: '2023-03-22T15:30:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 17,
    parentId: 16,
    userId: 1,
    text: "It's fascinating to think about how the younger philosopher might be influenced by their older self. Would they adopt the same ideas, or develop an entirely new philosophy?",
    createdAt: '2023-03-22T15:45:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 18,
    parentId: 17,
    userId: 4,
    text: 'Or what if they tried to change history and prevent certain philosophical ideas from being developed? Imagine the ripple effect that could have!',
    createdAt: '2023-03-22T16:00:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 19,
    parentId: 18,
    userId: 3,
    text: 'Wow, that could lead to a completely different development of human thought and society!',
    createdAt: '2023-03-22T16:15:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 20,
    parentId: 19,
    userId: 2,
    text: "But would they really be able to change history, or is the timeline fixed? That's another philosophical debate in itself.",
    createdAt: '2023-03-22T16:30:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 21,
    parentId: 20,
    userId: 1,
    text: "It's like a never-ending rabbit hole of philosophical questions!",
    createdAt: '2023-03-22T16:45:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 22,
    parentId: 21,
    userId: 4,
    text: "Exactly! That's what makes this kind of thought experiment so intriguing.",
    createdAt: '2023-03-22T17:00:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 23,
    parentId: 22,
    userId: 3,
    text: 'And we could apply this thought experiment to different historical figures, not just philosophers. Imagine the potential impact on science, art, and politics!',
    createdAt: '2023-03-22T17:15:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 24,
    parentId: 23,
    userId: 1,
    text: "Indeed, the possibilities are endless! It's fascinating to think about how a single conversation could potentially change the course of history.",
    createdAt: '2023-03-22T17:30:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 25,
    parentId: null,
    userId: 1,
    text: "As technology continues to advance, the line between humans and machines becomes increasingly blurred. We're reaching a point where we have to consider the ethical implications of creating highly intelligent machines capable of complex thought, decision-making, and even emotions. How do you think society should approach these ethical challenges, and what principles should guide our decisions?",
    createdAt: '2023-03-23T10:00:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 26,
    parentId: 25,
    userId: 2,
    text: 'One of the most important principles should be ensuring the well-being of all sentient beings, including AI. If we create machines with the capacity to suffer, we have a responsibility to prevent that suffering.',
    createdAt: '2023-03-23T10:15:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 27,
    parentId: 25,
    userId: 3,
    text: 'Transparency is also crucial. As we develop more advanced AI, we should be open about the algorithms and decision-making processes that underlie their behavior, in order to avoid hidden biases and promote trust.',
    createdAt: '2023-03-23T10:30:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 28,
    parentId: 25,
    userId: 4,
    text: 'I believe we should prioritize the development of AI for the greater good, focusing on applications that can help solve global problems like climate change, poverty, and disease, rather than using AI for purely commercial or military purposes.',
    createdAt: '2023-03-23T10:45:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 29,
    parentId: 25,
    userId: 1,
    text: 'We should also consider the impact of AI on employment and labor markets. As AI takes over more jobs, we need to think about how to ensure a fair distribution of resources and opportunities for human workers.',
    createdAt: '2023-03-23T11:00:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 30,
    parentId: 3,
    userId: 5,
    text: 'Relax bro',
    createdAt: '2023-03-23T11:15:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
  {
    id: 31,
    parentId: null,
    userId: 1,
    text: "The world of philosophy is vast, encompassing a myriad of topics that span from the nature of reality and existence to ethics, morality, and the pursuit of happiness. Throughout history, philosophers have attempted to understand the human condition, to explore the depths of our consciousness, and to grapple with the complexity of our interactions with one another and the world around us. Some of the most influential philosophers, such as Plato, Aristotle, Kant, and Nietzsche, have left their mark on the way we think about ourselves and the universe. As we continue to advance as a society, our understanding of these philosophical questions evolves, and new perspectives emerge. In the modern era, we face a unique set of challenges, many of which are brought on by rapid technological advancements and the growth of artificial intelligence. These developments force us to reevaluate our ethical frameworks and our understanding of what it means to be human. In this ever-changing landscape, it's crucial to engage in discussions that consider the implications of our actions and the potential consequences of the choices we make. By examining the ideas of philosophers from different periods and cultures, we can gain valuable insights into the nature of our own existence and develop a more comprehensive understanding of the world around us.",
    createdAt: '2023-03-23T13:00:00.000Z',
    imageLink: null,
    textFileLink: null,
  },
];
